## Raffle Game Related Constants
RAFFLE_STATUS_NOT_RUNNING = 0
RAFFLE_STATUS_RUNNING = 1
RAFFLE_STATUS_ENDED = 2

RAFFLE_GAME_INITIAL_POT = 100

## Ticket Constants
TICKET_PRICE = 5
TICKET_N_NUMS = 5
TICKET_MIN_COMPONENT = 1
TICKET_MAX_COMPONENT = 15
TICKET_VALID_NUM = tuple([i for i in range(TICKET_MIN_COMPONENT, TICKET_MAX_COMPONENT + 1)])

## Common constants
MIN_TICKETS_PER_USER = 1
MAX_TICKETS_PER_USER = 5